### ISSUE TITLE
Inconsistancy in the image colors

### ISSUE THREAD

**Issue by janrtvld** [animo/siera-desktop#120]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/60812202/231673365-d5b68795-a84a-4bea-8d7f-8190d2ab10df.png">

<img width="301" alt="image" src="https://user-images.githubusercontent.com/60812202/231673385-a2218c57-70bb-4066-bcd6-ad6dbe3a5f80.png">

The agent image has black text, while the credential image has white text. I think white text looks best for all images.

**Comment by Tommylans** [comment]
We don't have this behaviour anymore in the application.
